// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/webrtc/offer": {
            "post": {
                "description": "Accepts a WebRTC SDP offer and returns an SDP answer. Available when transport is smallwebrtc or both.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webrtc"
                ],
                "summary": "Submit WebRTC offer",
                "parameters": [
                    {
                        "description": "SDP offer string",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_server.webrtcOfferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_server.webrtcOfferResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid offer payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to start transport",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service unavailable (e.g. Opus encoder unavailable)",
                        "schema": {
                            "$ref": "#/definitions/pkg_server.webrtcErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pkg_server.webrtcErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "pkg_server.webrtcOfferRequest": {
            "type": "object",
            "properties": {
                "offer": {
                    "type": "string"
                }
            }
        },
        "pkg_server.webrtcOfferResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Voxray API",
	Description:      "Voxray voice pipeline server: WebSocket and WebRTC transport endpoints.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
